name = "s3broker-worker"
main = "src/index.ts"
compatibility_date = "2025-12-25"

# Update these routes to your own values
routes = [{ pattern = "sakimori.waga.me", custom_domain = true }]
workers_dev = false
preview_urls = false

[observability]
enabled = true

[vars]
# S3-compatible endpoint (e.g., Cloudflare R2)
S3_ENDPOINT = "https://7116748e83acc204c3a6df8b20aa5619.r2.cloudflarestorage.com"

# The following are set in wrangler secret:
# CLIENT_ACCESS_KEY_ID
# CLIENT_SECRET_ACCESS_KEY
# UPSTREAM_ACCESS_KEY_ID
# UPSTREAM_SECRET_ACCESS_KEY
